### ISSUE TITLE
no-response error occurs sometimes

### ISSUE THREAD

**Issue by topninja** [nuxt-community/workbox-cdn#23]
I am using latest nuxt version.
while develop or deploy to site after build, sometimes I can see no-response error via workbox-cdn package.
I attached screenshot.
![image](https://user-images.githubusercontent.com/47001971/93206805-f8500380-f727-11ea-9074-4791bdd238cd.png)
what's the reason?
thanks

**Comment by patrickcate** [comment]
I've been seeing this error as well.

**Comment by atinux** [comment]
Could you provide a reproduction please?

**Comment by pi0** [comment]
Please see response from [workbox maintainer](https://github.com/nuxt-community/pwa-module/issues/176#issuecomment-665722983). This error happens if network request fails for any reason.

But commonly this is an issue with [chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=823392) that when devtools is active (which is also valid during lighthouse) that makes wrong cors caching header that fails request.

If using nuxt pwa, simply upgrading to latest version will resolve issue. Otherwise, take a look at this fix: https://github.com/nuxt-community/pwa-module/pull/417
